services:
  postgres:
    container_name: booking_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=booking_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '54321:5432'
    volumes:
      - /Users/Shared/db/booking-db/:/var/lib/postgresql/data
